nataliakif/IceCream-project8

src/sass/components/_subtitile.scss
src/sass/components/_title.scss
src/sass/main.scss

добавил общие стили title и subtitle. изменил порядок подключения partial variables выше чем common, так как в common уже используются переменные объявленные в variables

title+subtitle-classes-added

---

src/partials/header.html

Пробный , так как не тянет обновления с мейна .

привет мир-удаление заголовка

---

src/sass/base/_common.scss

Прихований title (заголовок)
.visually-hidden

Прихований заголовок

---

src/sass/base/_variables.scss

Добавила цвета для ховера 2х кнопок и фона секций

добавление цветов

---

src/sass/components/_subtitile.scss
src/sass/components/_title.scss

доделал под разные размеры экрана - разный размер шрифта title и subtitle

title-subtitle-fontsize-fix

---

src/sass/base/_common.scss
src/sass/main.scss
src/sass/utils/_visually-hidden.scss

Скриваємо заголовок
.visually-hidden {
position: absolute;
width: 1 px;
height: 1 px;
margin: -1 px;
border: 0;
padding: 0;
white-space: nowrap;
clip-path: inset(100%);
clip: rect(0 0 0 0);
overflow: hidden;
}
і підключаємо main.scss

add Utils + .visually-hidden

---

src/sass/components/_container.scss

Изменения контейнера, чтобы корректно отображался при ширине экрана 320px

Обновление контейнера

---

src/partials/gallery.html
src/sass/layout/_gallery.scss

исправление небольшой ошибки в названии класса 

---

src/sass/base/_variables.scss
src/sass/components/_button.scss
src/sass/main.scss

Добавляет стили для кнопки и цвета

---

src/sass/layout/_gallery.scss

fix  gallery width

---

src/partials/about.html
src/sass/layout/_about.scss

Обновил кнопку, чтобы получше было

update button в секции about

---

src/partials/reviews.html
src/sass/components/_button.scss
src/sass/layout/_reviews.scss

button fix

---

src/index.html
src/js/about-modal.js
src/js/franchize-modal.js
src/js/map-modal.js
src/partials/about-modal.html
src/sass/components/_about-modal.scss
src/sass/components/_modal.scss

добавил блокировку скрола основной страницы при открытии модального окна. и добавил вертикальные скролы на модальные окна при высоте экрана < чем само модальное окно

modals-height-scroll-fix

---

src/sass/base/_common.scss

Обновил img

---

src/sass/components/_title.scss

изменил ширину 1200 -> 1280

---

src/partials/about.html
src/sass/components/_about-modal.scss

Добавил модальное окно

---

src/sass/components/_backdrop.scss

Добавил z-index, чтобы при использовании TAB (focus) секция Наташи не накладывалась сверху модалки

Добавил z-index

---

src/partials/about.html
src/sass/components/_about-modal.scss

Reverts nataliakif/IceCream-project8#63

Revert "Добавил модальное окно"

---

src/partials/about.html
src/sass/layout/_about.scss

Добавил кнопку и отцентрировал корову

BagFix-About

---

src/index.html
src/partials/map-form.html
src/sass/base/_modern-normalize.scss
src/sass/main.scss

local-normalize-add

---

src/partials/contacts.html
src/sass/layout/_contacts.scss

Добавила в секцию кнопки, так же внесла корректировки по предыдущему комиту.

contacts button

---

src/js/map-modal.js
src/partials/map-form.html
src/sass/components/_modal.scss

js и картинки от гугл. карт (а их там овер много) загружаются только после нажатия на кнопку maps

google-maps-low-performance-fix

---

src/partials/about-modal.html
src/partials/franchize-form.html
src/partials/map-form.html

удалил временные кнопки на открытие модальных окон

remove-temp-modal-buttons-from-page

---

src/sass/layout/_about.scss

Добавил маржин на подзаголовок и центрирование

fix-подзаголовок секции about

---

src/sass/base/_common.scss

  cursor: default;

---

src/partials/products.html
src/sass/layout/_products.scss

save section

---

src/partials/contacts.html
src/sass/layout/_contacts.scss

Внесла корректировки в семантику кода. (результата в css не увидела).

corrections code, contacts

---

src/sass/layout/_products.scss

button_hover

---

src/partials/gallery.html

gallery fix (ul, li)

---

src/sass/layout/_about.scss

Молоко поменял

---

src/partials/advantages.html
src/sass/utils/_visually-hidden.scss

visually-hidden

---

src/partials/franchize-form.html
src/partials/products.html
src/sass/components/_backdrop.scss

перевел контактную форму на английский, на кнопки в секции products добавил aria-label, так как кнопки без текста

franchize-modal-language-change

---

src/partials/about.html
src/partials/gallery.html
src/partials/reviews.html

добавил на все <img> loading="lazy"

img-loading-lazy
